FROM mhart/alpine-node:4.6

MAINTAINER Ben Simpson, ben@newcrossfoodcoop.org.uk

# This definition is used by drone builds

RUN apk update
RUN apk add git
RUN npm install -g gulp abao osprey-mock-service

WORKDIR /home/app

ADD package.json /home/app/package.json
RUN npm install
